name: Install Packages
description: '使用 Python 安裝專案與擴充套件依賴'

runs:
  using: "composite" 
  steps:  
    - name: Run Setup Dependencies Script
      # 在 GitHub Runner 中，不論 Win 或 Mac，直接寫 python 即可
      # 我們使用 -u (unbuffered) 確保 log 能即時印出
      shell: python
      run: |
        import subprocess
        import os
        
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'setup-deps.py')
        
        if os.path.exists(script_path):
            subprocess.run(['python', '-u', script_path], check=True)
        else:
            print(f"❌ Cannot find script at {script_path}")
            exit(1)