name: Install Packages
description: '使用 Python 安裝專案與擴充套件依賴'

runs:
  using: "composite" 
  steps:  
    - name: Run Setup Dependencies Script
      shell: python
      run: |
        import subprocess
        import os
        import sys
        
        # 1. 取得腳本路徑
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'setup-deps.py')
        
        # 2. 準備環境變數 (確保子程序也用 UTF-8)
        custom_env = os.environ.copy()
        custom_env["PYTHONUTF8"] = "1"
        
        if os.path.exists(script_path):
            # 使用 -X utf8 強制開啟 UTF-8 模式
            # 使用 -u 確保 log 即時印出
            subprocess.run(['python', '-X', 'utf8', '-u', script_path], check=True, env=custom_env)
        else:
            print(f"Cannot find script at {script_path}")
            sys.exit(1)