name: Install Packages
description: '使用 Python 安裝專案與擴充套件依賴'

runs:
  using: "composite" 
  steps:  
    - name: Run Setup Dependencies Script
      shell: python
      run: |
        import subprocess
        import os
        import sys
        
        # 強制設定環境變數，讓子程序也使用 UTF-8
        env = os.environ.copy()
        env["PYTHONUTF8"] = "1"
        
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'setup-deps.py')
        
        if os.path.exists(script_path):
            # 傳入 env=env
            subprocess.run(['python', '-u', script_path], check=True, env=env)
        else:
            print(f"❌ Cannot find script at {script_path}")
            sys.exit(1)