name: Upload Release
description: '上傳 Release 包'

inputs:
  environment:
    description: '環境'
    required: true
    default: 'development'
    type: choice
    options:
      - development
      - test
      - production

  platform:
    description: '平台'
    required: true
    default: 'windows'
    type: choice
    options:
      - windows
      - android
      - ios

  dev_mode:
    description: '開發者模式'
    required: true
    default: true
    type: boolean

  version_name:
    description: '版本名稱'
    required: true
    default: '1.0.0'
    type: string

  signing_type:
    description: '簽名類型'
    required: false
    default: 'debug'
    type: choice
    options:
      - debug
      - release

  bundle_code:
    description: 'Bundle Code'
    required: false
    default: ''
    type: string

runs:
  using: "composite" 
  steps:  
    - name: 1. Collect Assets
      id: collect
      shell: python
      env:
        PYTHONUTF8: "1"
        PYTHONUNBUFFERED: "1" # 加入這一行，確保所有 print 立即顯示
        PLATFORM: ${{ inputs.platform }}
        ENVIRONMENT: ${{ inputs.environment }}
        DEV_MODE: ${{ inputs.dev_mode }}
      run: |
        import subprocess, os, sys
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'pack_build.py')
        
        # 確保環境變數正確傳遞
        custom_env = os.environ.copy()
        custom_env["PYTHONUTF8"] = "1"
        
        if os.path.exists(script_path):
            # 重點：移除 stdout/stderr 的攔截，直接讓它輸出到 parent process
            # 並加上 -u (unbuffered) 參數確保即時性
            result = subprocess.run(
                ['python', '-u', script_path], 
                check=True, 
                env=custom_env,
                # 這裡不設定 stdout=PIPE，就會直接印在 GitHub Actions Log
            )
        else:
            print(f"❌ Script not found: {script_path}")
            sys.exit(1)

    - name: 2. Smart Rename
      id: rename
      shell: python
      env:
        PYTHONUTF8: "1"
        PYTHONUNBUFFERED: "1" # 加入這一行，確保所有 print 立即顯示
        COLLECTED_PATH: ${{ steps.collect.outputs.collected_path }}
        IN_VERSION_NAME: ${{ inputs.version_name }}
        IN_ENVIRONMENT: ${{ inputs.environment }}
        IN_SIGNING_TYPE: ${{ inputs.signing_type }}
        IN_BUNDLE_CODE: ${{ inputs.bundle_code }}
        PLATFORM: ${{ inputs.platform }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        import subprocess, os, sys
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'rename_build.py')
        
        # 確保環境變數正確傳遞
        custom_env = os.environ.copy()
        custom_env["PYTHONUTF8"] = "1"
        
        if os.path.exists(script_path):
            # 重點：移除 stdout/stderr 的攔截，直接讓它輸出到 parent process
            # 並加上 -u (unbuffered) 參數確保即時性
            result = subprocess.run(
                ['python', '-u', script_path], 
                check=True, 
                env=custom_env,
                # 這裡不設定 stdout=PIPE，就會直接印在 GitHub Actions Log
            )
        else:
            print(f"❌ Script not found: {script_path}")
            sys.exit(1)

    - name: 3. Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.rename.outputs.artifact_path }}
        tag_name: ${{ steps.rename.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ github.token }}