name: Update & Deploy bundles
description: '上傳資料'

inputs:
  environment:
    description: '環境'
    required: true
    default: 'development'
    type: choice
    options:
      - development
      - test
      - production

  platform:
    description: '平台'
    required: true
    default: 'windows'
    type: choice
    options:
      - windows
      - android
      - ios

  dev_mode:
    description: '開發者模式'
    required: true
    default: true
    type: boolean

runs:
  using: "composite" 
  steps:  
    - name: check out
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        clean: false

    - name: Install Packages
      uses: ./.github/actions/install-packages

    - name: Build Bundle
      uses: ./.github/actions/build-core
      with:
        git_token: ${{ github.token }} 
        force_clean: false
        environment: ${{ inputs.environment }}
        platform: ${{ inputs.platform }}
        dev_mode: ${{ inputs.dev_mode }}
        auto_compile: false
        version_name: ${{ inputs.version_name }}

    - name: Upload Bundle
      uses: ./.github/actions/upload-bundles
      with:
        environment: ${{ inputs.environment }}
        platform: ${{ inputs.platform }}
        dev_mode: ${{ inputs.dev_mode }}
        version_name: ${{ inputs.version_name }}