name: Update & Deploy bundles
description: '上傳資料'

inputs:
  environment:
    description: '環境'
    required: true
    default: 'development'
    type: choice
    options:
      - development
      - test
      - production

  platform:
    description: '平台'
    required: true
    default: 'windows'
    type: choice
    options:
      - windows
      - android
      - ios

  dev_mode:
    description: '開發者模式'
    required: true
    default: true
    type: boolean

runs:
  using: "composite" 
  steps:  
    - name: check out
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        clean: false

    - name: Install Packages
      uses: ./.github/actions/install-packages

    - name: Build Bundle
      uses: ./.github/actions/build-core
      with:
        git_token: ${{ github.token }} 
        force_clean: false
        environment: ${{ inputs.environment }}
        platform: ${{ inputs.platform }}
        dev_mode: ${{ inputs.dev_mode }}
        auto_compile: false

    - name: Prepare Remote Assets for Pages
      shell: python
      env:
        PYTHONUTF8: "1"
        PLATFORM: ${{ inputs.platform }}
      run: |
        import subprocess, os
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'prepare-remote.py')
        subprocess.run(['python', '-u', script_path], check=True)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.git_token || github.token }}
        publish_dir: ./public_pages # 這裡要對應 Python 腳本產出的目錄
        # keep_files: true # 如果你不想覆蓋舊的 Bundle，可以開啟此選項
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: gh-pages


  build_ios:
    runs-on: [self-hosted]

    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          clean: false

      - name: Install Packages
        uses: ./.github/actions/install-packages

      - name: Build Bundle(iOS)
        uses: ./.github/actions/build-core
        with:
          git_token: ${{ github.token }} 
          force_clean: false
          environment: 'production'
          platform: ios
          dev_mode: false
          auto_compile: false