name: Build Bundle
description: '打包資源&建置流程'

inputs:
  editor_path:
    description: 'Editor位置'
    required: true
    default: 'macOS'
    type: choice
    options: 
      - windows
      - macOS

  platform:
    description: '平台'
    required: true
    default: 'windows'
    type: choice
    options:
      - windows
      - android
      - ios

  environment:
    description: '環境'
    required: true
    default: 'development'
    type: choice
    options:
      - development
      - test
      - production

  dev_mode:
    description: '開發者模式'
    required: true
    default: true
    type: boolean

  version_name:
    description: '版本名稱'
    required: true
    default: '1.2.12'
    type: string

  git_token:
    description: 'Git Token'
    required: true

  force_clean:
    description: '是否強制清理'
    required: false
    default: 'true'

  auto_compile:
    description: '是否產生執行檔'
    required: false
    default: false

runs:
  using: "composite" 
  steps:   
    - name: Setup Environment Variables
      shell: python
      env:
        PYTHONUTF8: "1"
      run: |
        import os, platform
        # 根據系統判斷路徑
        win_path = r"D:\Program Files\Cocos\Editors\Creator\3.8.8\CocosCreator.exe"
        mac_path = "/Applications/Cocos/CocosCreator.app/Contents/MacOS/CocosCreator"
        
        # 判斷當前 Runner OS 並寫入環境變數
        cocos_path = win_path if platform.system() == "Windows" else mac_path
        
        with open(os.environ['GITHUB_ENV'], 'a', encoding='utf-8') as f:
            f.write(f"COCOS_PATH={cocos_path}\n")
        print(f"✅ Set COCOS_PATH to: {cocos_path}")

    # - name: Checkout Source
    #   uses: actions/checkout@v4
    #   with:
    #     submodules: false
    #     token: ${{ inputs.git_token || github.token }}
    #     lfs: true
    #     clean: ${{ inputs.force_clean }}
    
    - name: Configure Engine Macro (CC_DEBUG)
      shell: python
      env:
        PYTHONUTF8: "1"
        DEV_MODE: ${{ inputs.dev_mode }}
      run: |
        import subprocess, os, sys
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'configure-engine.py')
        custom_env = os.environ.copy()
        custom_env["PYTHONUTF8"] = "1"
        if os.path.exists(script_path):
            subprocess.run(['python', '-X', 'utf8', '-u', script_path], check=True, env=custom_env)
        else:
            print(f"❌ Cannot find script at {script_path}"); sys.exit(1)

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'   

    - name: Build Cocos Project
      shell: python
      env:
        PYTHONUTF8: "1"
        PYTHONUNBUFFERED: "1" # 加入這一行，確保所有 print 立即顯示
        PLATFORM: ${{ inputs.platform }}
        DEV_MODE: ${{ inputs.dev_mode }}
        AUTO_COMPILE: ${{ inputs.auto_compile }}
        ENVIRONMENT: ${{ inputs.environment }}
        VERSION_NAME: ${{ inputs.version_name }}
      run: |
        import subprocess, os, sys
        script_path = os.path.join(os.environ['GITHUB_WORKSPACE'], '.github', 'tools', 'build-cocos.py')
        
        # 確保環境變數正確傳遞
        custom_env = os.environ.copy()
        custom_env["PYTHONUTF8"] = "1"
        
        if os.path.exists(script_path):
            # 重點：移除 stdout/stderr 的攔截，直接讓它輸出到 parent process
            # 並加上 -u (unbuffered) 參數確保即時性
            result = subprocess.run(
                ['python', '-u', script_path], 
                check=True, 
                env=custom_env,
                # 這裡不設定 stdout=PIPE，就會直接印在 GitHub Actions Log
            )
        else:
            print(f"❌ Script not found: {script_path}")
            sys.exit(1)